dinocards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('main.urls')),
    path('', include('forum.urls')),
    path('', include('manager.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('select_card/<int:transaction_id>/', views.select_card_view, name='select_card'),
    path('make_offer/<int:transaction_id>/<int:card_id>/', views.make_offer, name='make_offer'),
    path('toggle_transaction/<int:card_id>/<str:next_page>/', views.toggle_transaction, name='toggle_transaction'),
    path('toggle_sale/<int:card_id>/', views.SellCreationView.as_view(), name='toggle_sale'),
    path('remove_sale/<int:sell_id>/<str:next_page>', views.remove_sell, name='remove_sale'),
    path('offers/<int:transaction_id>/', views.offers_view, name='offers'),
    path('offer_reply/<int:offer_id>/<int:reply>/', views.offer_reply, name='offer_reply'),
    path('buy/<int:sell_id>/', views.buy, name='buy'),
]

manager/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

urlpatterns = [
    path('edit/', views.edit, name='edit'),
    path('remove_user/', views.remove_user, name='remove_user'),
    path('create_card/', views.CreateCardView.as_view(), name='create_card'),
    path('delete_card/', views.delete_card, name='delete_card'),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Card(models.Model):
    class Rarity(models.IntegerChoices):
        D = 200,
        C = 500,
        B = 800,
        A = 1000,

    name = models.CharField(max_length=60, unique=True)
    description = models.CharField(max_length=300)
    rarity_rate = models.PositiveIntegerField(choices=Rarity.choices)
    image = models.URLField(max_length=200)

    def __str__(self):
        return f'card id:{self.id} value:{self.rarity_rate}'


class Deck(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cards = models.ManyToManyField(Card, related_name='cards', blank=True)


class Transaction(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


class Offer(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class Sell(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms


class RemoveUser(forms.Form):
    username = forms.CharField()


class DeleteCard(forms.Form):
    name = forms.CharField()

manager/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import DeleteView, CreateView, FormView, DetailView

from main.models import Card
from manager.forms import RemoveUser, DeleteCard


@user_passes_test(lambda u: u.is_superuser)
def edit(request):
    cards = Card.objects.all()
    context = {'cards': cards}
    return render(request, 'edit.html', context)


@user_passes_test(lambda u: u.is_superuser)
def remove_user(request):
    if request.method == 'POST':
        form = RemoveUser(request.POST)

        if form.is_valid():
            rem = get_object_or_404(User, username=form.cleaned_data['username'])
            if rem is not None:
                rem.delete()
                return redirect('edit')
    else:
        form = RemoveUser()
    context = {'form': form}
    return render(request, 'delete_user.html', context)


class CreateCardView(LoginRequiredMixin, CreateView):
    model = Card
    fields = '__all__'
    template_name = 'create_card.html'

    def form_valid(self, form):
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('home')


@user_passes_test(lambda u: u.is_superuser)
def delete_card(request):
    if request.method == 'POST':
        form = DeleteCard(request.POST)

        if form.is_valid():
            rem = get_object_or_404(Card, name=form.cleaned_data['name'])
            if rem is not None:
                rem.delete()
                return redirect('edit')
    else:
        form = DeleteCard()
    context = {'form': form}
    return render(request, 'delete_card.html', context)

manager/templates/create_card.html
{% extends "partials/base.html" %}
{% block content %}
    <h1 class="my-3">Create Card</h1>
    {% load django_bootstrap5 %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        <div class="container mt-3">
            <input type="submit" value="submit" class="btn btn-secondary">
        </div>
    </form>
{% endblock %}

manager/templates/delete_card.html
{% extends "partials/base.html" %}
{% block content %}
    <h1 class="my-3">Delete Card</h1>
    {% load django_bootstrap5 %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="container mt-3">
            <input type="submit" value="submit" class="btn btn-secondary">
        </div>
    </form>
{% endblock %}

manager/templates/delete_user.html
{% extends "partials/base.html" %}
{% block content %}
    <h1 class="my-3">Remove User</h1>
    {% load django_bootstrap5 %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="container mt-3">
            <input type="submit" value="submit" class="btn btn-secondary">
        </div>
    </form>
{% endblock %}

manager/templates/edit.html
{% extends "partials/base.html" %}
{% block content %}
    {% load static %}

    <h4 class="my-3">Admin</h4>
    <br>
    <a href="{% url 'remove_user' %}" class="ms-1">Delete a user</a>
    <br>
    <br>
    <a href="{% url 'create_card' %}" class="ms-1">Create new cards</a>
    <br>
    <br>
    <a href="{% url 'delete_card' %}" class="ms-1">Delete a card</a>
    <br>
    <h4 class="text-center">all cards</h4>
    <hr>
    <div class="row justify-content-center">
        {% for card in cards %}
            <div class="card p-0 m-3 col-md-6" style="width: 20rem; height: 30rem;">
                <div class="card-header" style="background-color: white">
                    <div class="row">
                        <h4 class="col"> {{ card.name }} </h4>
                        <div class="col ">
                            <div class="row justify-content-end">
                                {% if card.transaction_set.all %}
                                    {{ card.transaction_set.all.0.owner }}
                                    <img src="{% static card.transaction_set.all.0.owner.profile.profileType.img %}"
                                         alt=""
                                         style="max-height: 50px; max-width: 50px"
                                         class="d-inline-block align-text-top rounded-circle ms-3">

                                {% else %}
                                    {{ card.sell_set.all.0.owner }}
                                    <img src="{% static card.sell_set.all.0.owner.profile.profileType.img %}"
                                         alt=""
                                         style="max-height: 50px; max-width: 50px"
                                         class="d-inline-block align-text-top rounded-circle ms-3">
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

                <img src="{{ card.image }}" class="card-img-top" alt="" style="height: 10rem;">
                <div class="card-body">
                    <p class="card-text" style="font-size: .8rem">{{ card.description }} </p>
                </div>
            </div>

        {% endfor %}
    </div>



{% endblock %}